pub fn record() -> String {
    String::from(
        r#""Author","Source","Quote"
"J.S. Felts","","We often suffer more from our response to a difficulty, than from the difficulty itself. Panic and anxiety don't lessen what we are facing, they magnify it."
"Lucius Annaeus Seneca (the younger)","Hippolytus, Tragedies","'Tis safest, when in fear, to force the attack."
"Joseph Addison","The Spectator, 9 October 1712","This fear of any future difficulties or misfortune is so natural to the mind, that were a man’s sorrows and disquietudes summed up at the end of his life, it would generally be found that he had suffered more from the apprehension of such evils as never happened to him, than from those evils which had really befallen him. To this we may add, that among those evils which befall us, there are many which have been more painful to us in the prospect than by their actual pressure."
"Henry David Thoreau","Walden","The mass of men lead lives of quiet desperation."
"Oliver Wendell Holmes Sr.","Elsie Venner","When a resolute young fellow steps up to the great bully, the world, and takes him boldly by the beard, he is often surprised to find it comes off in his hand, and that it was only tied on to scare away the timid adventurers."
"Christian Nestell Bovee","Intuitions and Summaries of Thought","There is a great beauty in going through life fearlessly. Half our fears are baseless - the other half discreditable."
"Samuel Daniel","The Tragedy of Cleopatra, The Poetical Works of Mr. Samuel Daniel","The absent danger greater still appears less fears he who is near the thing he fears."
"Ralph Waldo Emerson","The American Scholar, speech, 31 August 1837","Fear always springs from ignorance."
"Napoleon Bonaparte","Aphorisms and Thoughts","He who fears being conquered is sure of defeat."
"Ovid","Epistulae ex Ponto","The wounded limb shrinks from the gentlest touch; and to the nervous the smallest shadow excites alarm."
"Bertrand Russell","An Outline of Intellectual Rubbish","Neither a man nor a crowd nor a nation can be trusted to act humanely or to think sanely under the influence of a great fear."
"Edmund Burke","A Philosophical Enquiry into the Origin of Our Ideas","No passion so effectually robs the mind of all its powers of acting and reasoning as fear."
"Franklin Delano Roosevelt","First inaugural address, 4 March 1933","The only thing we have to fear is fear itself - nameless, unreasoning, unjustified terror which paralyzes needed efforts to convert retreat into advance."
"Herodotus","The Histories","It is better by noble boldness to run the risk of being subject to half the evils we anticipate than to remain in cowardly listlessness for fear of what might happen."
"German Proverb","","Fear makes the wolf bigger than he is."
"Charles Wagner","Courage","Fear, like courage, is contagious. It must be resisted as soon as shown."
"Moorish Proverb","","He who fears something gives it power over him."
"Lucius Annaeus Seneca (the younger)","Moral Letters to Lucilius","We are more often frightened than hurt: our troubles spring more often from fancy than reality."
"Michel de Montaigne","Of Experience, Essays","He who fears he shall suffer, already suffers what he fears."
"Malay Proverb","","Fear to let fall a drop and you spill a lot."
"Joseph Farrell","About Impartiality, The Lectures of a Certain Professor","There are those who are so scrupulously afraid of doing wrong that they seldom venture to do anything."
"William Henry Burnham","The Normal Mind","The most drastic and usually the most effective remedy for fear is direct action."
"Leonardo da Vinci","The Notebooks","Just as courage imperils life, fear protects it."
"Edgar Watson Howe","Plain People","A good scare is worth more to a man than good advice."
"John Witherspoon","Ministerial Character and Duty, Sermons","It is only the fear of God, which can deliver us from the fear of men."
"John Henry Newman","Quoted in Character Lessons in American Biography (1909) by James White","Fear not that thy life shall come to an end, but rather fear that it shall never have a beginning."
"Sa'di","Gulistan","Were the diver to think on the jaws of the shark, he would never lay hands on the precious pearl."
"English Proverb","","He that will not sail till all dangers are over must never put to sea."
"Gaius Julius Caesar","The Gallic War","As a rule, what is out of sight disturbs men's minds more seriously than what they see."
"Edmund Burke","On Conciliation with the American Colonies, speech, 22 March 1775","The concessions of the weak are the concessions of fear."
"Ralph Waldo Emerson","Courage, Society and Solitude","Knowledge is the antidote to fear."
"George Eliot","Letter to Mrs. Pears, February 1842","To fear the examination of any proposition appears to me an intellectual and moral palsy that will ever hinder the firm grasping of any substance whatever."
"Antoine de Saint-Exupery","Wind, Sand and Stars","Once men are caught up in an event they cease to be afraid. Only the unknown frightens men."
"Thomas Fuller","Gnomologia","Better hazard once, than be always in fear."
"Henry Ward Beecher","The Faults of Character, The Herald of Health (1870)","I don't like these cold, precise, perfect people, who, in order not to speak wrong, never speak at all, and in order not to do wrong, do nothing."
"Herman Melville","Moby Dick","'I will have no man in my boat,' said Starbuck, 'who is not afraid of a whale.' By this, he seemed to mean not only that the most reliable and useful courage was that which arises from the fair estimation of the encountered peril, but that an utterly fearless man is a far more dangerous comrade than a coward."
"Inscription on the monument to Lord Lawrence at Westminster Abbey","","He feared man so little because he feared God so much."
"Jean Paul Richter","Quoted in Library of the World's Best Literature (1896) by Charles Warner","The timid fear before danger, the cowardly in the midst of it, and the courageous after it is over."
"French Proverb","","He who fears to suffer, suffers from fear."
"The Bible (KJV)","2 Timothy 1:7","For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."
"William Shakespeare","Measure for Measure","Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt."
"John Witherspoon","The Dominion of Providence over the Passions of Men, sermon, 17 May 1775","If your cause is just, if your principles are pure, and if your conduct is prudent, you need not fear the multitude of opposing hosts."
"Saying","","Those who fear nothing, love nothing."
"Benjamin Franklin","Poor Richard's Almanack","If evils come not, then our fears are vain; and if they do, fear but augments the pain."
"Mark Twain","Pudd'nhead Wilson","Courage is resistance to fear, mastery of fear - not absence of fear."
"George S. Patton","Speech to the Third Army before the invasion of France, June 1944","Every man is scared in his first battle. If he says he's not, he's a liar! Some men are cowards but they fight the same as the brave men or they get the hell slammed out of them watching men fight who are just as scared as they are. The real hero is the man who fights even though he is scared."
"Publilius Syrus","Sententiae","Audacity augments courage; hesitation, fear."
"Carl Von Clausewitz","On War","The great masses of people are timid by nature, and thereby danger is invariably exaggerated.""#
    )
}